### ISSUE TITLE
Flink相关问题

### ISSUE THREAD

**Issue by zhihui-ge** [NextMark/datashops#3]
1. 目前是不是还不支持Flinksql任务
2. 目前是不是支持yarn application提交任务，yarn session 和yarn per job还不支持？

**Comment by NextMark** [comment]
> 1. 目前是不是还不支持Flinksql任务
> 2. 目前是不是支持yarn application提交任务，yarn session 和yarn per job还不支持？

1. 已经支持flink sql任务的提交
2. yarn session和per job目前并不支持，尤其是per job使用场景逐渐会被application替代
